#!/usr/bin/python

import os


# casperimport

# modeled after munkiimport but for casper

# takes a path as input

# if path is a pkg -> upload

# if path is an .app -> pkg build -> upload

# if path is a dmg -> mount and act on contents

# upload to jss

# mount server if necessary

# copy pkg to caspershare/Packages

# create Package object with JSS API

